version: "3.8"

services:
  moq-relay:
    container_name: moq-relay
    image: moq-rs
    entrypoint: ["moq-relay"]
    network_mode: host
    user: 10002:10002
    environment:
      RUST_LOG: info
    volumes:
      - ./certs:/certs
      - /data/source:/output:rw
    command: --tls-cert /certs/cert.pem --tls-key /certs/privkey.pem  --listen '[::]:443' --vompc-url https://vompc-web.videodev.svt.se

  moq-redis:
    container_name: moq-redis
    image: redis:latest
    entrypoint: [ "moq-redis" ]
    ports:
      - "6400:6379"
    user: 10002:10002
    environment:
      RUST_LOG: info

  moq-live-scheduler:
    container_name: moq-live-scheduler
    image: moq-rs
    entrypoint: [ "moq-live-scheduler" ]
    network_mode: host
    user: 10002:10002
    environment:
      RUST_LOG: info
    volumes:
      - /root/.docker:/root/.docker
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./certs:/certs
      - /data/source:/output:rw
    command: --redis redis://localhost:6400 --vompc-url https://vompc-web.videodev.svt.se
