version: "3.8"

services:
  moq-relay:
    container_name: moq-relay
    image: moq-rs
    entrypoint: ["moq-relay"]
    network_mode: host
    user: 10002:10002
    environment:
      RUST_LOG: info
    volumes:
      - ./certs:/certs
      - ./dump:/dump:rw
      - /data/source:/output:rw
    command: --tls-cert /certs/cert.pem --tls-key /certs/privkey.pem  --listen '[::]:443' --vompc-url https://vompc-web.videodev.svt.se --subscriber-output /output/glas_till_glas/noencoder
