#!/bin/bash
set -euo pipefail

# Change directory to the root of the project
cd "$(dirname "$0")/.."

# Use debug logging by default
export RUST_LOG="${RUST_LOG:-debug}"

# Connect to localhost by default.
HOST="${HOST:-localhost}"
PORT="${PORT:-4443}"
ADDR="${ADDR:-$HOST:$PORT}"

# Generate a random 16 character name by default.
#NAME="${NAME:-$(head /dev/urandom | LC_ALL=C tr -dc 'a-zA-Z0-9' | head -c 16)}"

# JK use the name "test" instead
# TODO use that random name if the host is not localhost
NAME="${NAME:-test}"

# Combine the host and name into a URL.
URL="${URL:-"https://$ADDR/$NAME"}"

# Default to a source video
#INPUT="${INPUT:-dev/source.mp4}"

# eventually output to source dir of ER
OUTPUT="${OUTPUT:-out/en01}"

# Print out the watch URL
#echo "Watch URL: https://quic.video/watch/$NAME?server=$ADDR"

mkdir -p dump
rm dump/* || true

mkdir -p "$OUTPUT"
rm "$OUTPUT/*" || true

mkdir -p event-rec-out/


cargo run --bin moq-sub -- "$URL" "$@"
